"""empty message

Revision ID: 0c7bfd3e04b2
Revises: 1e587deff462
Create Date: 2024-03-13 20:03:06.047749

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '0c7bfd3e04b2'
down_revision: Union[str, None] = '1e587deff462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
